# Esercizio 1

Definire i  numpy array a=[1.2, 5.4, 6, 1.59] e b=[5.2, 1.2, 1.5, 2] ed eseguire le seguenti operazioni:
  - calcolare la radice quadrata degli elementi di a;
   - calcolare 𝑒xp(𝑎/2) ;
   - calcolare il vettore somma tra a e b ;
   - moltiplicare ogni elemento di a per il corrispondente elemento di b;
   - creare un vettore di valori uniformemente equispaziati tra 0 e 30 con passo  0.5;
   - creare un vettore di 100 valori uniformemente equispaziati tra 1 e 2.
   - usare linspace() per creare un numpy array 2x6 con prima riga di 6 valori uniformi compresi tra 10 e 20 e seconda riga 6 valori     
      uniformi compresi tra  20 e 10;
   - calcolare il prodotto scalare tra a e b;
   - creare la matrice A che ha come righe i vettori a e b ;
   - calcolare il prodotto scalare tra i due vettori a e b;
   - eseguire il prodotto della matrice A per il vettore b e assegnarlo ad y;
   - costruire una matrice diagonale D a partire dal vettore a;

In [8]:
import numpy as np
import math

a=np.array([1.2, 5.4, 6, 1.59])
b=np.array([5.2, 1.2, 1.5, 2 ])

a1 = np.sqrt(a)

a2= np.exp(a/2)

c= a + b

ab = a*b

equi30 = np.arange(0,30.5,0.5)

equi1_2 = np.linspace(1,2,100)

C = np.array([np.linspace(10, 20 , 6), np.linspace(20, 10 , 6)])

scalare_a_b = np.dot(a,b)

A = np.array([a,b])

y = A@b

D = np.diag(a)

print(y)





[24.9  34.73]


# Esercizio 2

Costruire  i seguenti Numpy array 2d utilizzando il minor numero di istruzioni possibili

<img src="ese2.png" width="500">

In [6]:
import numpy as np

A = np.full((3,3), 2)
A = np.concatenate((A, np.full((3,1),3)), 1)


B1 = np.vstack([np.linspace(1, 10, 10).reshape(1, -1)] * 3)  
B = np.hstack((2 * np.eye(3), B1))

a=np.ones((4,))*2
b=np.ones((3,))*(-1)
C= np.diag(a)+np.diag(b,-1)+np.diag(b,1)
print(B)

[[ 2.  0.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 0.  2.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 0.  0.  2.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]]


# Esercizio 3

Calcolare la somma dei primi n numeri naturali dispari sia utilizzando un ciclo for che servendosi dell'istruzione sum di numpy.

In [32]:
import numpy as np

n = 4
somma = 0

for i in range(1, n+1, 2):

    somma += i

print(somma)

a1 = np.array(list(range(1,n+1,2)))
sum = np.sum(a1)
print(sum)



4
4


# Esercizo 4

Scrivere una function Python per generare l'n-esimo termine (n > 2) della successione
di Fibonacci. Scrivere poi una function ricorsiva che risolva lo stesso problema
e confrontare i tempi di calcolo delle due functions per n = 24.

Ricordiamo la formula per generare i i numeri di Fibonacci:

$$F_0=1$$
$$F_1=1$$
$$F_n = F_{n-1} + F_{n-2}, \quad n=2,...$$

In [6]:
import time

from fibonacci_files import *

print(fibonacci(10000))


inf


/home/siralex/Desktop/Metodi_numerici/Lezione_2/fibonacci_files.py:10: RuntimeWarning: overflow encountered in scalar add
  f[k] = f[k-1] + f[k-2]
